#kubectl create configmap myindex --from-file=index-avenger.html
apiVersion: v1
kind: Pod
metadata:
  name: mycfgmappod
  labels:
        app: mycfgmappod
spec:
  containers:
  - name: tomcat
    image: "httpd"
    ports:
      - containerPort: 80
    volumeMounts:
    - name: indexdata
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: indexdata
    configMap:
      name: myindex
---
apiVersion: v1
kind: Service
metadata: 
  name: mycfgmapsvc
spec: 
  type: NodePort
  selector: 
    app: mycfgmappod
  ports: 
  - name: http
    nodePort: 30025
    port: 80
    protocol: TCP
  
