apiVersion: v1
kind: Pod
metadata:
  name: volpod
  labels:
    app: volpod
  #namespace: default 
spec:
  restartPolicy: Never
  containers:
  - name: volcontainer
    image: "httpd"
    volumeMounts:
    - name: volvolume
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: volvolume
    hostPath:
      path: /Users/lokeshkamalay/myindex #modify the path that you want to attach    

---
apiVersion: v1
kind: Service
metadata:
  name: volumesvc
spec:
  type: NodePort
  selector:
    app: volpod
  ports:
  - name: http
    nodePort: 30026
    port: 80
    protocol: TCP
